### ISSUE TITLE
Support charging saved cards

### ISSUE THREAD

**Issue by richardsplayground** [mattwire/com.drastikbydesign.stripe#14]
Hi,

I support an event-heavy organization where our users register for several events at one go.  They have asked for the ability to charge saved cards, similar to what Drupal Commerce does with their stripe integration.  That request has not gotten much love over on the [drastik original version of this extension](https://github.com/drastik/com.drastikbydesign.stripe/issues/122), but I'm wondering if it might be possible to get it working over here.  We would be up for contributing to the development of this feature.

**Comment by mattwire** [comment]
It should certainly be possible to do.  The Stripe API supports it.  We would need to have a little bit of a think about how it would work from a UI perspective though - do you have any thoughts?
@jmcclelland Any thoughts on this?

**Comment by jmcclelland** [comment]
Hm, I don't think this fits with any of our use cases. I may be wrong, but wouldn't this require that people have a log in on the site? 

For our groups - all contributions and event registrations are made as anonymous users and we explicitly prevent user account creation for security reasons.

If your site supports anonymous user account creation _and_ you have a critical mass of people who login before they make a payment, then this use case would be relevant. Otherwise, recurring contributions are the closest equivalent feature.

I don't mean to be a wet towel on the idea, but I think this would add lots of complication to benefit something that is more of a corner case that a foundational feature.

**Comment by richardsplayground** [comment]
Hi,

Actually @jmcclelland you are describing our exact scenario.  *All* of our users are registered as our site supports a closed community.  We only use CiviCRM to manage the records of our students.  As they attend many classes, they often complain about having to enter the same credit card number over and over again, and they wonder why we can support saved cards on one side of our web site but not on the event side.

I totally appreciate this situation will not fit all sites.  But it will fit many.

**Comment by mattwire** [comment]
@richardsplayground Can you contact me on the email address on my github profile - let's see if we can get some funding together for this.

**Comment by richardsplayground** [comment]
Hi @mattwire, I have emailed!  Thank you!

**Comment by mattwire** [comment]
Extension now at https://lab.civicrm.org/extensions/stripe
